export const requests = [
{id:'REQ-001',title:'Normalize alert ownership mapping',stakeholder:'Cloud Platform Lead',businessDriver:'Reduce unowned critical alerts',riskIfIgnored:'Delayed incident response',affectedTeams:['Cloud Platform','SecOps'],requestedOutcome:'Mapped ownership for tier-1 alerts',category:'Cloud monitoring',status:'Needs discovery',pmNextAction:'Define taxonomy scope'},
{id:'REQ-002',title:'Automated control evidence reminders',stakeholder:'GRC Lead',businessDriver:'Lower audit prep effort',riskIfIgnored:'Late evidence and findings',affectedTeams:['GRC','Security Engineering'],requestedOutcome:'Scheduled evidence reminders',category:'Control assurance',status:'Scored',pmNextAction:'Estimate reminder workflow effort'},
{id:'REQ-003',title:'Incident prioritization by asset criticality',stakeholder:'SecOps Manager',businessDriver:'Improve triage quality',riskIfIgnored:'High-value assets under-prioritized',affectedTeams:['SecOps','Platform'],requestedOutcome:'Criticality-aware triage rubric',category:'Incident readiness',status:'Committed',pmNextAction:'Track pilot outcomes'},
{id:'REQ-004',title:'Vulnerability SLA exceptions dashboard',stakeholder:'Engineering Director',businessDriver:'Transparent SLA exceptions',riskIfIgnored:'Untracked risk acceptance',affectedTeams:['Engineering','GRC'],requestedOutcome:'Exception visibility by BU',category:'Vulnerability management',status:'Needs discovery',pmNextAction:'Align SLA policy data sources'},
{id:'REQ-005',title:'Executive risk trend scorecard',stakeholder:'CISO',businessDriver:'Decision-ready monthly updates',riskIfIgnored:'Leadership blind spots',affectedTeams:['Security Leadership','GRC'],requestedOutcome:'Monthly risk trend package',category:'Executive reporting',status:'Scored',pmNextAction:'Draft scorecard metric set'},
{id:'REQ-006',title:'Control failure ownership traceability',stakeholder:'Internal Audit Partner',businessDriver:'Faster remediation ownership',riskIfIgnored:'Repeat audit findings',affectedTeams:['GRC','Platform'],requestedOutcome:'Named owners per failed control',category:'Control assurance',status:'New',pmNextAction:'Collect ownership mapping inputs'},
{id:'REQ-007',title:'Release readiness checklist for workflow changes',stakeholder:'Platform TPM',businessDriver:'Safer security workflow launches',riskIfIgnored:'Operational regressions',affectedTeams:['Platform','Security Engineering'],requestedOutcome:'Checklist with go/no-go criteria',category:'Adoption enablement',status:'Committed',pmNextAction:'Publish v1 checklist template'},
{id:'REQ-008',title:'Backlog scoring model for tool integrations',stakeholder:'Security Engineering Manager',businessDriver:'Consistent prioritization decisions',riskIfIgnored:'Roadmap churn and contention',affectedTeams:['Security Engineering','PMO'],requestedOutcome:'Shared scoring model',category:'Tooling/process automation',status:'Routed to operations',pmNextAction:'Coordinate operations-owned runbook'}
];

export const backlogItems = [
{epic:'Detection Quality',capability:'Normalize alert taxonomy',reach:7,impact:3,confidence:0.8,effort:4,riceScore:4.2,riskModifier:3,complianceModifier:1,adoptionModifier:1,executiveUrgencyModifier:1,adjustedPriority:10.2,priorityLabel:'P0',pmRecommendation:'Build now',blocked:false},
{epic:'Vulnerability Flow',capability:'Build vulnerability aging report',reach:8,impact:2,confidence:0.9,effort:4,riceScore:3.6,riskModifier:2,complianceModifier:2,adoptionModifier:1,executiveUrgencyModifier:0,adjustedPriority:8.6,priorityLabel:'P1',pmRecommendation:'Build now',blocked:false},
{epic:'Governance',capability:'Create control ownership map',reach:4,impact:2,confidence:0.7,effort:3,riceScore:1.9,riskModifier:3,complianceModifier:3,adoptionModifier:1,executiveUrgencyModifier:1,adjustedPriority:9.9,priorityLabel:'P0',pmRecommendation:'Requires executive decision',blocked:true},
{epic:'GRC Automation',capability:'Add automated evidence reminders',reach:5,impact:2,confidence:0.8,effort:3,riceScore:2.7,riskModifier:2,complianceModifier:3,adoptionModifier:0,executiveUrgencyModifier:1,adjustedPriority:8.7,priorityLabel:'P1',pmRecommendation:'Build now',blocked:false},
{epic:'Incident Readiness',capability:'Create incident prioritization model',reach:6,impact:3,confidence:0.7,effort:5,riceScore:2.5,riskModifier:3,complianceModifier:1,adoptionModifier:1,executiveUrgencyModifier:1,adjustedPriority:8.5,priorityLabel:'P1',pmRecommendation:'Investigate with stakeholders',blocked:true},
{epic:'Executive Reporting',capability:'Publish monthly executive scorecard',reach:3,impact:2,confidence:0.8,effort:2,riceScore:2.4,riskModifier:1,complianceModifier:2,adoptionModifier:0,executiveUrgencyModifier:2,adjustedPriority:7.4,priorityLabel:'P2',pmRecommendation:'Schedule next roadmap cycle',blocked:false},
{epic:'Adoption Operations',capability:'Add adoption tracker for released workflows',reach:6,impact:2,confidence:0.8,effort:3,riceScore:3.2,riskModifier:1,complianceModifier:1,adoptionModifier:3,executiveUrgencyModifier:1,adjustedPriority:9.2,priorityLabel:'P0',pmRecommendation:'Build now',blocked:false},
{epic:'Decision Governance',capability:'Create decision log for roadmap tradeoffs',reach:4,impact:2,confidence:0.9,effort:2,riceScore:3.6,riskModifier:1,complianceModifier:1,adoptionModifier:1,executiveUrgencyModifier:2,adjustedPriority:8.6,priorityLabel:'P1',pmRecommendation:'Build now',blocked:false}
];
export const roadmapPhases=[{phase:1,name:'Baseline Visibility',objective:'Establish shared intake, backlog, and risk visibility.',deliverables:['Intake table','Initial backlog scoring','Risk/decision log'],exitCriteria:'All new requests routed through intake and scored within one cycle.',dependencies:'Stakeholder owners assigned',risks:'Unclear ownership across teams',adoptionSignal:'At least 70% of requests entered through intake flow.'},{phase:2,name:'Automation and Prioritization',objective:'Increase throughput with repeatable prioritization and reminders.',deliverables:['Evidence reminders','Vulnerability aging report','Priority filter dashboard'],exitCriteria:'Monthly reprioritization uses adjusted scoring model.',dependencies:'Data source mapping complete',risks:'Low confidence data quality',adoptionSignal:'PM and GRC leads use dashboard in weekly execution review.'},{phase:3,name:'Governance and Control Validation',objective:'Improve control accountability and traceability.',deliverables:['Control ownership map','Evidence traceability table','Remediation action tracking'],exitCriteria:'Control owners assigned and validation cadence stable.',dependencies:'Control framework alignment',risks:'Control owners overcommitted',adoptionSignal:'Evidence reviewed on schedule for priority controls.'},{phase:4,name:'Executive Reporting and Continuous Improvement',objective:'Support quarterly decisions with trend and adoption outcomes.',deliverables:['Executive scorecard','Roadmap tradeoff log','Adoption intervention plans'],exitCriteria:'Executive reviews capture explicit decisions and owners.',dependencies:'Leadership review cadence',risks:'Decision latency',adoptionSignal:'Executive decisions logged and followed up each cycle.'}];
export const adoptionItems=[{capability:'Alert ownership mapping',owningTeam:'Cloud Platform',targetUsers:'SecOps on-call',adoptionStatus:'Piloting',adoptionMetric:'% teams using workflow',currentAdoptionSignal:'2 of 5 teams onboarded',friction:'Legacy alert labels',nextPmAction:'Run enablement office hours'},{capability:'Evidence reminders',owningTeam:'GRC',targetUsers:'Control owners',adoptionStatus:'Needs intervention',adoptionMetric:'Evidence collected on schedule',currentAdoptionSignal:'58% on-time submissions',friction:'Owners unsure of deadlines',nextPmAction:'Add escalation path'},{capability:'Incident prioritization model',owningTeam:'SecOps',targetUsers:'Incident commanders',adoptionStatus:'Adopted by early users',adoptionMetric:'Reduction in repeated issues',currentAdoptionSignal:'14% fewer repeat incidents',friction:'Asset criticality tags incomplete',nextPmAction:'Align with asset inventory team'},{capability:'Executive decision log',owningTeam:'Security PMO',targetUsers:'Security leadership',adoptionStatus:'Broad adoption',adoptionMetric:'Executive decisions logged',currentAdoptionSignal:'100% decisions logged last month',friction:'None reported',nextPmAction:'Maintain quarterly quality review'},{capability:'Release readiness checklist',owningTeam:'Platform TPM Office',targetUsers:'Engineering release managers',adoptionStatus:'Not started',adoptionMetric:'SLA adherence after rollout',currentAdoptionSignal:'Template drafted only',friction:'No release owner onboarding yet',nextPmAction:'Schedule pilot with one platform train'}];
export const riskDecisions=[{id:'RD-001',description:'Control ownership remains ambiguous for two high-risk controls.',impact:'High',likelihood:'Medium',owner:'GRC Lead',action:'Confirm accountable owners in steering meeting',dueDate:'2026-06-05',status:'Decision needed'},{id:'RD-002',description:'Incident prioritization depends on incomplete asset criticality data.',impact:'High',likelihood:'High',owner:'SecOps Lead',action:'Mitigate with interim manual criticality mapping',dueDate:'2026-05-30',status:'Mitigating'},{id:'RD-003',description:'Evidence reminders may create notification fatigue.',impact:'Medium',likelihood:'Medium',owner:'Security PM',action:'Pilot cadence and measure response rates',dueDate:'2026-06-12',status:'Open'},{id:'RD-004',description:'Executive scorecard scope expanded beyond MVP capacity.',impact:'Medium',likelihood:'Medium',owner:'CISO Chief of Staff',action:'Approve reduced MVP metric set',dueDate:'2026-06-03',status:'Decision needed'}];
export const controlEvidence=[{controlArea:'Alerting coverage',evidenceSource:'Detection configuration export',owner:'SecOps Lead',validationCadence:'Monthly',currentStatus:'Partial',lastReviewed:'2026-05-15',remediationAction:'Close unmapped alert owners'},{controlArea:'Vulnerability remediation SLA',evidenceSource:'Ticket aging report',owner:'Engineering Security PM',validationCadence:'Weekly',currentStatus:'At risk',lastReviewed:'2026-05-20',remediationAction:'Escalate over-SLA exceptions'},{controlArea:'Incident runbook readiness',evidenceSource:'Tabletop exercise notes',owner:'Incident Response Manager',validationCadence:'Quarterly',currentStatus:'On track',lastReviewed:'2026-04-28',remediationAction:'Update escalation contacts'},{controlArea:'Control ownership',evidenceSource:'Control responsibility matrix',owner:'GRC Lead',validationCadence:'Monthly',currentStatus:'Partial',lastReviewed:'2026-05-10',remediationAction:'Assign remaining owners'},{controlArea:'Evidence collection',evidenceSource:'Reminder completion logs',owner:'GRC Operations',validationCadence:'Monthly',currentStatus:'At risk',lastReviewed:'2026-05-18',remediationAction:'Enable manager escalation'},{controlArea:'Executive reporting cadence',evidenceSource:'Monthly scorecard archive',owner:'Security PMO',validationCadence:'Monthly',currentStatus:'On track',lastReviewed:'2026-05-22',remediationAction:'None'}];
